---
- block:

  - name: Mostrar parametro
    debug: msg="{{mensaje}}"

  - name: Instalar nginx
    apt:
      name: nginx

  rescue:
    - name: Capturar un error
      debug: msg="Hubo un error :S"
