- block:
  - name: Crear archivo de configuracion
    template:
      src: templates/config.tpl
      dest: /etc/nginx/sites-available/default
      mode: "u=rw,g=r,o=r"

  - name: Pagina de inicio
    template:
      src: templates/index.html.tpl
      dest: /var/www/html/index.html
      mode: "u=rw,g=r,o=r"

  - name: Reiniciar nginx
    service:
      name: nginx
      state: restarted
