---
- hosts: all
  become: True
  # vars:
  #   - nombre: Sergiooooo

  vars_files:
    - group_vars/vault.yml

  tasks:
    - name: Mostrar un mensaje
      debug: msg="Prueba local de variables"

    - name: Mensaje con variables
      debug: msg="Nombre -> {{nombre}} Apellido -> {{apellido}}"
      delegate_to: 127.0.0.1
